version: "3.9"

volumes:
  mongodb-data:
    driver: local
  python-packages:
    driver: local

services:
  web:
    build: .
    stdin_open: true
    tty: true
    environment:
      DEBUG: 1
    command:
      - /bin/bash
      - -c
      - |
        pip install -q --upgrade -r ./requirements/development.txt
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app:rw
      - ./.version:/app/.version:rw
      - ~/.aws:/root/.aws
      - python-packages:/usr/local/lib/python3.11/site-packages:rw,delegated
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb

  debugpy:
    build: .
    stdin_open: true
    tty: true
    environment:
      DEBUG: 1
    command:
      - /bin/bash
      - -c
      - |
        pip install -q --upgrade -r ./requirements/development.txt
        python3 -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app:rw
      - ./.version:/app/.version:rw
      - ~/.aws:/root/.aws
      - python-packages:/usr/local/lib/python3.11/site-packages:rw,delegated
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    command: mongod --quiet --logpath /dev/null
